-- Copyright (c) 2026 Samvel Safaryan. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
-- Authors: Samvel Safaryan <samvelsafaryan1313@gmail.com>

import BasicCategoryTheory.Introduction
import BasicCategoryTheory.Chapter1_CategoriesFunctorsAndNaturalTransformations.Categories
import BasicCategoryTheory.Chapter1_CategoriesFunctorsAndNaturalTransformations.Functors
import BasicCategoryTheory.Chapter1_CategoriesFunctorsAndNaturalTransformations.NaturalTransformations
import BasicCategoryTheory.Chapter2_Adjoints.Adjoints
import BasicCategoryTheory.Chapter3_InterludeOnSets.ConstructionsWithSets
import BasicCategoryTheory.Chapter3_InterludeOnSets.SmallAndLargeCategories
import BasicCategoryTheory.Chapter4_Representables.DefinitionsAndExamples
import BasicCategoryTheory.Chapter4_Representables.YonedaLemma
import BasicCategoryTheory.Chapter4_Representables.ConsequencesOfTheYonedaLemma
import BasicCategoryTheory.Chapter5_Limits.LimitsAndExamples
import BasicCategoryTheory.Chapter5_Limits.ColimitsAndExamples
import BasicCategoryTheory.Chapter5_Limits.InteractionsBetweenFunctorsAndLimits
import BasicCategoryTheory.Chapter6_AdjointsRepresentablesAndLimits.LimitsInTermsOfRepresentablesAndAdjoints
